### ISSUE TITLE
tls_co & tcp_co does not work anymore on flowgger 0.2.0

### ISSUE THREAD

**Issue by edefaria** [jedisct1/flowgger#9]
I use this docker image :
https://hub.docker.com/r/jedisct1/flowgger/builds/budnck6eugg9crdccv3ufsb/

Input section example : 

```
################## 
#  Input section  #
###################
[input]
type = "tls_co"
format = "ltsv"
listen = "0.0.0.0:12201"
framing = "line"   
tls_threads = 2
tls_cert = "/etc/ssl/private/flowgger.pem"
tls_key = "/etc/ssl/private/flowgger.pem"
tls_ca_file = "/etc/ssl/private/flowgger.pem"
tls_method = "any" 
```

Logs: 

```
Flowgger v0.2.0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Scheduler missing") }) }', ../src/libcore/result.rs:788
stack backtrace:   
   1:     0x7fc2b4a3984b - <unknown>
   2:     0x7fc2b4a3968e - <unknown>
   3:     0x7fc2b4a374d0 - <unknown>
   4:     0x7fc2b4a3666e - <unknown>
   5:     0x7fc2b4a3859e - <unknown>
   6:     0x7fc2b4a3815a - <unknown>
   7:     0x7fc2b4a495b8 - <unknown>
   8:     0x7fc2b49752cc - <unknown>
   9:     0x7fc2b4941bd8 - <unknown>
  10:     0x7fc2b493e98f - <unknown>
  11:     0x7fc2b4935429 - <unknown>
  12:     0x7fc2b4a45df8 - <unknown>
  13:     0x7fc2b4a460db - <unknown>
  14:     0x7fc2b493f510 - <unknown>
  15:     0x7fc2b40da82f - __libc_start_main
  16:     0x7fc2b4934ca8 - <unknown>
  17:                0x0 - <unknown>
```

Same with "tcp_co" :

```
Flowgger v0.2.0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Scheduler missing") }) }', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x7f626427384b - <unknown>
   2:     0x7f626427368e - <unknown>
   3:     0x7f62642714d0 - <unknown>
   4:     0x7f626427066e - <unknown>
   5:     0x7f626427259e - <unknown>
   6:     0x7f626427215a - <unknown>
   7:     0x7f62642835b8 - <unknown>
   8:     0x7f62641af2cc - <unknown>
   9:     0x7f626417dfe5 - <unknown>
  10:     0x7f626417898f - <unknown>
  11:     0x7f626416f429 - <unknown>
  12:     0x7f626427fdf8 - <unknown>
  13:     0x7f62642800db - <unknown>
  14:     0x7f6264179510 - <unknown>
  15:     0x7f626391482f - __libc_start_main
  16:     0x7f626416eca8 - <unknown>
  17:                0x0 - <unknown>
```

**Comment by jedisct1** [comment]
0.2.0 hasn't been released yet.

**Comment by jedisct1** [comment]
Version 0.2.0 was released, with major changes to the Kafka driver. I don't expect any breakage, but please report any!
